### ISSUE TITLE
mod was removed 

### ISSUE THREAD

**Issue by sophienix** [Elaina69/Yes-Steve-Model-Repo#3]
why was this mod was removed from curse forge and modrinth

**Comment by Fate099** [comment]
Same question, tried to find this mod but all I got is "Error 404's/Page Not Found", It feels safer when downloading it on Forge and Modrinth but since it got removed it gave me a suspicion that this mod might be harmful.

**Comment by Elaina69** [comment]
> Same question, tried to find this mod but all I got is "Error 404's/Page Not Found", It feels safer when downloading it on Forge and Modrinth but since it got removed it gave me a suspicion that this mod might be harmful.



> why was this mod was removed from curse forge and modrinth

Currently, we are trying to contact Modrinth to re-upload the mod. Previously, Modrinth deleted Yes Steve Model because the mod's model security code was mistaken for a virus
