### ISSUE TITLE
Skadi model in the repo is actually a dupe of AL's Ägir

### ISSUE THREAD

**Issue by Lirieva** [Elaina69/Yes-Steve-Model-Repo#5]
First time reporting anything in github so hope this is the right way, but yeah, as title says, Skadi the corrupting heart's model is actually a duplicate of Ägir's model

https://github.com/Elaina69/Yes-Steve-Model-Repo/blob/main/ak_skadi_the_corrupting_heart.ysm

![skadi agir](https://github.com/user-attachments/assets/e2d2d894-c43a-4031-8a4a-3b43742cd741)

**Comment by Elaina69** [comment]
ok that's my problem, i will change that
thanks for your report
